name = "sentry-proxy-worker"
main = "src/index.ts"
compatibility_date = "2024-01-29"

# modify the following to match your environment
[vars]
ALLOWED_DSN = ""
SENTRY_INGEST_DOMAIN = "ingest.sentry.io"
